# Generated by Django 3.0.8 on 2020-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(default=250, verbose_name='Size in ml'),
        ),
    ]
