# Generated by Django 3.0.8 on 2020-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200904_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=10, verbose_name='Current Stock'),
        ),
    ]
